@echo off
REM ============================================================
REM  Health-ID Vault — Database Environment Setup
REM  Run this ONCE before starting the application.
REM ============================================================

echo.
echo  *** Health-ID Vault Database Setup ***
echo.

REM ── 1. Configurable settings ────────────────────────────────
set DB_HOST=localhost
set DB_PORT=3306
set DB_NAME=health_vault
set DB_USER=root
set DB_PASS=your_mysql_password
set MYSQL_CMD=mysql

REM ── 2. Check MySQL is reachable ─────────────────────────────
echo [1/3] Checking MySQL connection...
%MYSQL_CMD% -h%DB_HOST% -P%DB_PORT% -u%DB_USER% -p%DB_PASS% -e "SELECT 1;" >nul 2>&1
IF ERRORLEVEL 1 (
    echo  ERROR: Cannot connect to MySQL at %DB_HOST%:%DB_PORT%
    echo  Make sure MySQL is running and credentials in this script are correct.
    pause
    exit /b 1
)
echo  OK — MySQL is reachable.

REM ── 3. Create database if not exists ────────────────────────
echo [2/3] Creating database '%DB_NAME%' if not exists...
%MYSQL_CMD% -h%DB_HOST% -P%DB_PORT% -u%DB_USER% -p%DB_PASS% -e "CREATE DATABASE IF NOT EXISTS %DB_NAME% CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>&1
IF ERRORLEVEL 1 (
    echo  ERROR: Failed to create database.
    pause
    exit /b 1
)
echo  OK — Database ready.

REM ── 4. Apply schema ─────────────────────────────────────────
echo [3/3] Applying schema from database\schema.sql ...
%MYSQL_CMD% -h%DB_HOST% -P%DB_PORT% -u%DB_USER% -p%DB_PASS% %DB_NAME% < database\schema.sql 2>&1
IF ERRORLEVEL 1 (
    echo  WARNING: Schema may already be applied (duplicate table errors are safe to ignore).
) ELSE (
    echo  OK — Schema applied.
)

REM ── 5. Write database.properties ────────────────────────────
echo.
echo Updating src\main\resources\database.properties ...
(
  echo # Auto-generated by setup_db.bat — edit manually if needed
  echo db.url=jdbc:mysql://%DB_HOST%:%DB_PORT%/%DB_NAME%
  echo db.username=%DB_USER%
  echo db.password=%DB_PASS%
  echo db.driver=com.mysql.cj.jdbc.Driver
) > src\main\resources\database.properties
echo  OK — database.properties updated.

echo.
echo  Setup complete! You can now run the application.
echo.
pause
